services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:10000 app:app"
    plan: free
    autoDeploy: true
    rootDir: backend
    
  - type: web
    name: react-frontend
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "serve -s build"
    staticPublishPath: build
    plan: free
    autoDeploy: true
    rootDir: frontend
