services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
    plan: free
    autoDeploy: true
    rootDir: backend
    
  - type: web
    runtime: static
    name: elotracker
    staticPublishPath: build
    previews:
      generation: automatic # Enable service previews
    rootDir: frontend
